### ISSUE TITLE
What may cause the exporter to OOM?

### ISSUE THREAD

**Issue by alfieyfc** [Strech/sidekiq-prometheus-exporter#37] opened 2021-02-17 10:37 UTC
We are seeing some spikes in RAM consumption with both `0.1.13` and `0.1.15` versions, wondering what could've caused them.

![image](https://user-images.githubusercontent.com/41598103/108190415-dfbb9d80-714c-11eb-819f-0e98e301faf4.png)

While running under our K8s setup policies (requiring resource limitations), these spikes causes `sidekiq-prometheus-exporter` pods to exit with OOM, then restart, but no significant logs to be observed. We've tried setting memory limits for the container from 500Mi to 4Gi, however even with 4Gi this still happens, which seems odd since we didn't expect an exporter to consume so much resource.

I'm submitting this issue hoping to understand what types of events could trigger the exporter to consume more RAM than usual.

**Comment by Strech** [comment] 2021-02-18 09:00
Hello @alfieyfc we can identify it by answering a list of questions:

1. Which metrics are you using? Only `standard`?
2. How many sidekiq queues do you have?
3. How many sidekiq workers do you have?

In `standard` metrics only 3 are not pre-calculated. It's `sidekiq_queue_latency_seconds`, `sidekiq_queue_enqueued_jobs` and `sidekiq_queue_max_processing_time_seconds`. They are using [Sidekiq API](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb) to get most of the abstractions, but it has a cost.

P.S if you like the project you can [support it ❤️](https://github.com/Strech/sidekiq-prometheus-exporter#if-you-like-the-project-and-want-to-support-me-on-my-sleepless-nights-you-can), any help is appreciated

**Comment by alfieyfc** [comment] 2021-02-19 04:38
Hi @Strech Thanks for the reply!

We looked at the settings and verified with monitoring dashboard, that 
1. We're indeed using `standard` metrics only
2. We have 33 queues defined in our config yaml. However I noticed the metrics `sidekiq_queue` can vary depending on the queue. Not really sure where this metrics is defined since it's not in this repo's readme.
3. Using the metrics `sidekiq_workers` we see the numbers vary over time, most of the time it's about 100 and goes up to 280 at max

Looking just at the dashboard, I haven't been able to tell the correlations between exporter memory usage and any of the above :( Currently my plan is to observe correlations with sidekiq instances, but tbh I'm just aiming cluelessly... 

![image](https://user-images.githubusercontent.com/41598103/108458157-042f8b00-72af-11eb-9cdd-bba851278b5c.png)

I'll keep investigating and share any further progress here.

**Comment by Strech** [comment] 2021-02-19 08:33
@alfieyfc Do I understand graphs correct that `Memory Usage`'s red line is an exporter memory usage and it jumps to 1Gb?

> We have 33 queues defined in our config yaml. However I noticed the metrics sidekiq_queue can vary depending on the queue. Not really sure where this metrics is defined since it's not in this repo's readme.

It's indeed not in the project. Can you tell me what's written in `sidekiq_queue` metrics? Because I don't have such a metric defined.

And how do you calculate the memory usage of the pod? Because Graphana may draw the spikes like that randomly and re-drawing them on reload. So can you share:

1. Which statement is written for `sidekiq_queue` metric
2. How you compute memory usage of the `metrics` pod
3. What the `metrics` pod restarted? Do you see it in k8s?

**Comment by Strech** [comment] 2021-02-19 08:43
About `sidekiq_queue` seems like it's a copy of `sidekiq_queue_enqueued_jobs` and might be obsolete

**Comment by alfieyfc** [comment] 2021-02-22 06:25
@Strech Sorry I was out during the weekend, here are my feedbacks on stuff:
1. You were correct on reading `Memory Usage`'s red line jumping, but it's not really about above or below 1GB. It jumps several times over a period, which to me is reasonable if they are using Sidekiq API to get most of the abstractions with a cost. However, we need to somewhat "predict" how much it consumes is considered "normal". 
Using the screenshot as an example, there were jumps over 1GB two times. Should we set the K8s Pod's `spec.containers[].resources.limits.memory` set to 1Gi, the Pod would crash with an OOM error.
As mentioned in original issue, setting `spec.containers[].resources.limits.memory` to 4Gi still encountered OOM since the exporter's consumption is over 4GB from time to time.
2. The `Memory Usage` is using 
    ```
    container_memory_usage_bytes{namespace="default",pod=~"sidekiq-prometheus-exporter-.*"}
    ```
    `container_memory_usage_bytes` I believe is from the `node-exporter`s
3. I'm not quite sure what you meant by `the metrics pod restarted`. In K8s, all we're seeing is
    ```bash
    $ kubectl get po
    NAME                                                         READY   STATUS      RESTARTS
    sidekiq-prometheus-exporter-7b64fc6c5d-gwprc                 1/1     Running     4
    ```
    ```bash
    $ kubectl describe po sidekiq-prometheus-exporter-7b64fc6c5d-gwprc        ## I'm skipping unrelated output
    Containers:
      sidekiq-prometheus-exporter:
        Last State:     Terminated
          Reason:       OOMKilled
          Exit Code:    137
    ```
4. Also not sure where to go with `how do you run the metrics pod?` The `sidekiq-prometheus-exporter` was directly pulled from your DockerHub repo, and run it in K8s with a YAML configuration file. I don't know what a `rack file` is 😅 The YAML looks something like this:
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
    labels:
        app: sidekiq-prometheus-exporter
    name: sidekiq-prometheus-exporter
    namespace: default
    spec:
    replicas: 1
    selector:
        matchLabels:
        app: sidekiq-prometheus-exporter
    template:
        metadata:
        annotations:
            prometheus.io/port: "9292"
            prometheus.io/scrape: "true"
        labels:
            app: sidekiq-prometheus-exporter
        spec:
        containers:
        - env:
            - name: REDIS_URL
            value: redis://my-redis-sidekiq-svc:6379
            - name: LINES
            value: "42"
            - name: COLUMNS
            value: "178"
            image: strech/sidekiq-prometheus-exporter:0.1.15
            name: sidekiq-prometheus-exporter
            ports:
            - containerPort: 9292
            protocol: TCP
            resources:
            limits:
                cpu: 100m
                memory: 1Gi
            requests:
                cpu: 50m
                memory: 200Mi
    ```

**Comment by alfieyfc** [comment] 2021-02-22 07:03
About `sidekiq_queue`, I found out that was another exporter written by my colleague before we adapted this repo. That exporter only collects number of enqueued jobs in queue, which is exactly the same as `sidekiq_queue_enqueued_jobs`. 

Would it have anything to do with this exporter consuming RAM?

**Comment by Strech** [comment] 2021-02-22 08:29
Thanks for the clarification. Let me try to set up a test installation with a more-less similar workload and some measurements. Maybe I can get insights into what is going on

**Comment by Strech** [comment] 2021-02-26 08:11
Hey @alfieyfc I did memory performance tests and also checked company projects.

For my local installation, I've tried to recreate a load pattern from your screenshot.

Setup:

1. 4 queues with different names
2. 3 job classes with different names (1 slow, 1 failing, 1 normal)
3. more than 5K jobs scheduled each 15-30 seconds
4. up to 6m on sleep time in the slow job
5. huge JSON arguments for all normal jobs (with random strings and all kind of data)
6. every 200ms a separate container with curl will ask for metrics
7. every 5 seconds Prometheus will scrape metrics
8. up to 50ms on `/metrics` response time
9. 2Kb size of `/metrics` response

7 hours of intense work looks like this

<img width="776" alt="8ks7b 2021-02-26 08-30-40" src="https://user-images.githubusercontent.com/920053/109272035-a05a1480-7810-11eb-8456-b2715cc523c9.png">

The last 30 minutes looks like this

<img width="776" alt="18t78 2021-02-26 08-33-42" src="https://user-images.githubusercontent.com/920053/109272753-9b499500-7811-11eb-81f1-53984a51e501.png">

I think I can share this setup (if you want) and you will extend it to generate the memory leak, but till that, I have some suspects. I've seen a memory leak a few times when metrics response grows over time drastically due to unique labels. So let's set another list of questions/measures that will help to identify the root cause:

1. What is the size of `/metrics` response when the memory comes to be > 500Mb
2. How jobs `args` payload looks like? Is it a huge set of data or a few IDs here and there?
3. How many queues do you have and do you have any dynamic naming in there?
4. Can you share `/metrics` response that I can see how does it look like? Maybe I can spot something?
5. The max execution time is close to 16m in some of your jobs, are they regular and how many of those are running?
6. What other sidekiq plugins do you use? I have concerns that they can patch sidekiq data and as a result, you will get leaks. Can you share the list?
7. Which sidekiq version are you running outside metrics container?

**Comment by alfieyfc** [comment] 2021-02-26 09:11
@Strech Thanks for the incredible work! 

Looks like it's some issue from our setup then (don't think we have jobs as many as over millions) . I'll check with the questions listed and see what I can share for further collaboration over next week and keep you posted!

**Comment by Strech** [comment] 2021-02-26 11:31
@alfieyfc I've pushed to this branch a folder `issue-37` where you can find an entire setup for load testing https://github.com/Strech/sidekiq-prometheus-exporter/tree/issue-37/issue-37

**Comment by Strech** [comment] 2021-02-27 09:33
Just in case I've tested it over 12h of intense work again with the latest files in the `issue-37` branch and the results are the same – no leak.

I still feel that I want to create a pattern with lots of long-running jobs, to have the same-ish as your pattern, but so far it looks like this

#### Last 1h
<img width="776" alt="8tbk4 2021-02-27 08-25-41" src="https://user-images.githubusercontent.com/920053/109383453-e41f4d80-78e6-11eb-9afd-5f8499237a4d.png">

#### Last 12h
<img width="776" alt="qage3 2021-02-27 08-25-12" src="https://user-images.githubusercontent.com/920053/109383455-e681a780-78e6-11eb-84c7-05a986f6299b.png">

**Comment by Strech** [comment] 2021-03-05 12:42
@alfieyfc Hey, do you succeed with this issue resolution? Should I close it or it's still relevant?

**Comment by alfieyfc** [comment] 2021-03-09 08:03
@Strech Sorry for the late reply. Here are some updates with some mixed feelings 😅 

First off, it was just now clarified to me that we didn't directly use your docker image from DockerHub. Instead, we actually built it with the `sidekiq-prometheus-exporter` gem. I'm truly sorry about the misinformation. Dockerfile and Gemfile are as below:

Dockerfile:
```Dockerfile
FROM mycr/myrepo/ruby:2.7.2-jemalloc

RUN  apt-get upgrade -y \
    && addgroup --system exporter \
    && adduser --system --shell /bin/false --disabled-password --no-create-home --gecos exporter exporter

USER exporter
WORKDIR /app
ADD config.ru config.ru Gemfile /app
RUN bundle update && bundle install --system --retry 5

EXPOSE 9292
ENTRYPOINT [ "rackup" ]
CMD [ "-p", "9292", "-o", "0.0.0.0", "config.ru" ]
```

Gemfile:
```Gemfile
source 'https://rubygems.org'

ruby '2.7.2'

gem 'rack'
gem 'sidekiq', '~> 6.1.2'
gem 'redis-namespace'
gem 'sidekiq-prometheus-exporter'
```

---

Secondly, we tried some random ways and somehow got rid of the OOM situation. Here's what we did:
1. Rollback `sidekiq` version in Gemfile to `5.2.8` from `6.1.2`, rebuilt image, OOM persisted.
2. Re-upgrade `sidekiq` version in Gemfile to `6.1.2`, rebuilt image, haven't encountered OOM for over a week!

Compared to our original situation, where OOM occurs multiple times everyday, it seems that the issue can be considered resolved.

> Btw, my colleague decided to alter `sidekiq` versions because from the discussion above he suspected it was a problem from sidekiq's API. Still weird that it kinda fixed itself after rebuilding with the same version though.

**Comment by Strech** [comment] 2021-03-09 14:27
Woah, great news. I see one potential suspect from your Dockerfile `ruby:2.7.2-jemalloc`, also I see unlocked `rack` and `redis-namespace` which potentially can contribute to the issue.

I would recommend locking all versions and double-check the ruby base image. But anyways, happy that the issue gets resolved.

**Closed by Strech** 2021-03-09 14:27 UTC
Labels: clarification needed, invalid
